const mysql = require('mysql2/promise');

function slugify(text) {
  return text.toLowerCase().trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .substring(0, 100);
}

const contents = {
  1: `<p>After months of building, testing and listening to our users, we are thrilled to announce <strong>ProjectHub 2.0</strong> — the biggest update we have ever shipped.</p><h2>What is new?</h2><p>We rebuilt the entire frontend from scratch using Next.js 14 with the App Router. Pages load in under 200ms, real-time updates are instant, and the UI feels completely native.</p><h2>Real-time everywhere</h2><p>Every task update, comment, and status change now propagates to all team members instantly via WebSockets. No more refreshing the page to see what your teammates are doing.</p><h2>New Kanban board</h2><p>The redesigned Kanban board supports drag-and-drop across columns, bulk actions, and inline editing. You can now manage an entire sprint without leaving the board view.</p><h2>What is next?</h2><p>We are working on AI-powered task suggestions, time tracking, and a mobile app. Stay tuned — the best is yet to come.</p>`,
  2: `<p>When ProjectHub hit 50,000 active users, our WebSocket server started showing cracks. Connections were dropping, latency was spiking, and our on-call engineer was not sleeping well.</p><h2>The problem</h2><p>We were running a single Node.js WebSocket server. Every connection held state in memory. When we scaled horizontally, clients connected to different servers could not communicate with each other.</p><h2>The solution: Redis Pub/Sub</h2><p>We introduced Redis as a message broker between WebSocket server instances. When a message arrives on server A, it publishes to a Redis channel. All other servers subscribe and forward the message to their connected clients.</p><h2>Connection pooling</h2><p>We also moved from one connection per user to a pooled model where each server handles up to 10,000 connections using worker threads. This cut our server count from 20 to 3.</p><h2>Results</h2><p>We now handle 100,000 concurrent connections with p99 latency under 40ms. Our infrastructure bill dropped by 60%.</p>`,
  3: `<p>Most teams waste hours every week on tasks that should take minutes. Here are the ten habits that the most productive teams on ProjectHub share.</p><h2>1. Write tasks as outcomes, not actions</h2><p>Instead of writing "Update homepage", write "Homepage loads in under 2 seconds on mobile". Outcome-based tasks are easier to prioritise and verify.</p><h2>2. Use the two-minute rule</h2><p>If a task takes less than two minutes, do it immediately instead of adding it to the board. This keeps your backlog clean and your mind clear.</p><h2>3. Time-box your sprints</h2><p>Fixed-length sprints create healthy urgency. Two-week sprints work best for most teams — long enough to ship something meaningful, short enough to course-correct.</p><h2>4. Daily standups under 15 minutes</h2><p>Three questions only: What did you do yesterday? What will you do today? What is blocking you? Anything else goes into a separate meeting.</p><h2>5. Review and retrospect every sprint</h2><p>Teams that hold regular retrospectives improve their velocity by an average of 23% over six months. Make it a non-negotiable ritual.</p>`,
  4: `<p>ProjectHub started as a weekend project. I needed a better way to manage my freelance clients and could not find a tool that felt right. So I built one.</p><h2>Month 1: Zero users</h2><p>I launched on a Sunday evening with a post on a developer forum. By Monday morning I had 47 sign-ups. By Friday I had 200. The product was rough but people were using it.</p><h2>Month 3: First 1,000 users</h2><p>Word of mouth was the only channel that worked. I focused entirely on making existing users happy. Every support email got a personal reply within an hour.</p><h2>Month 6: Product-market fit</h2><p>When users started saying they could not imagine working without ProjectHub, I knew we had something. Churn dropped below 5% and referrals started compounding.</p><h2>Month 12: 10,000 users</h2><p>We launched a Pro plan, ran our first paid campaign, and got featured in a popular newsletter. The combination pushed us past 10,000 users in a single week.</p><h2>Lessons learned</h2><p>Build for a specific person, not everyone. Talk to your users every day. Ship fast and fix faster. The rest takes care of itself.</p>`,
  5: `<p>DesignCo is a 40-person design agency based in Jaipur. Before ProjectHub, they were managing client projects across spreadsheets, email threads and a whiteboard in the conference room.</p><h2>The problem</h2><p>Projects were consistently delivered late. Clients were frustrated. The team was spending more time in status meetings than doing actual design work.</p><h2>The switch</h2><p>DesignCo migrated to ProjectHub in a single weekend. They imported their active projects, invited their team, and set up client-facing views so customers could track progress in real time.</p><h2>The results</h2><p>Within 90 days, on-time delivery jumped from 40% to 100%. Client satisfaction scores hit an all-time high. The team cut their weekly meeting time by 4 hours.</p><blockquote><p>"ProjectHub gave us back our Friday afternoons." — Head of Delivery, DesignCo</p></blockquote>`,
  6: `<p>Notifications are one of those features that look simple from the outside and are brutally complex on the inside. Here is how we built ours.</p><h2>Requirements</h2><p>We needed notifications to be real-time, persistent, and delivered even when the user is not currently on the page. We also needed them to work across multiple browser tabs.</p><h2>Architecture</h2><p>We use a hybrid approach: WebSockets for real-time delivery when the user is online, and a database-backed queue for delivery when they are offline. When a user opens the app, we fetch unread notifications and then subscribe to the WebSocket channel.</p><h2>The broadcast problem</h2><p>When a task is updated, we need to notify potentially dozens of users. We solved this with a fan-out pattern: one database write triggers a background job that creates individual notification records and broadcasts via Redis Pub/Sub.</p><h2>Read state</h2><p>We track read state per notification per user. A single API call marks all notifications as read and updates the badge count in real time across all open tabs.</p>`,
  7: `<p>Sprint reviews have a reputation for being the most boring meeting in the agile calendar. They do not have to be. Here are five techniques that will transform yours.</p><h2>1. Demo, do not report</h2><p>Show working software, not slides. A two-minute live demo is worth ten minutes of status updates. If it is not demoable, it is not done.</p><h2>2. Invite a real user</h2><p>Once a month, bring an actual customer into your sprint review. Their reactions will tell you more than any analytics dashboard.</p><h2>3. Celebrate small wins</h2><p>Acknowledge every task that shipped, not just the big features. Teams that celebrate small wins have higher morale and lower turnover.</p><h2>4. Make the backlog visible</h2><p>Show what is coming next. When the team can see the roadmap, they make better decisions about what to prioritise today.</p><h2>5. End with one commitment</h2><p>Close every review with a single team commitment for the next sprint. One clear goal beats a list of ten vague intentions every time.</p>`,
  8: `<p>Enterprise teams have complex permission needs. A developer should not be able to delete a project. A client should be able to view progress but not edit tasks. Custom roles make this possible.</p><h2>How it works</h2><p>Admins can now create roles with granular permissions across six categories: Projects, Tasks, Members, Documents, Chat, and Billing. Each permission can be set to None, View, Edit, or Manage.</p><h2>Role inheritance</h2><p>Roles can inherit from a parent role. This means you can create a "Senior Developer" role that has all Developer permissions plus the ability to manage tasks.</p><h2>Audit log</h2><p>Every permission change is logged with a timestamp and the admin who made the change. This gives enterprise customers the audit trail they need for compliance.</p><h2>Getting started</h2><p>Custom roles are available on the Enterprise plan. Head to Settings then Roles to create your first custom role.</p>`,
  9: `<p>When we started ProjectHub, we chose MySQL almost by default. As we grew, we revisited that decision seriously. Here is what we found.</p><h2>Why we considered switching</h2><p>PostgreSQL has better support for JSON operations, more advanced indexing options, and a stronger reputation in the developer community. Several engineers on the team had PostgreSQL experience and advocated for a migration.</p><h2>Why we stayed with MySQL</h2><p>Our workload is read-heavy with simple queries. MySQL query cache and connection pooling performed better in our benchmarks for this pattern. We also had significant operational knowledge invested in MySQL.</p><h2>The real lesson</h2><p>The best database is the one your team knows well and that fits your access patterns. Both MySQL and PostgreSQL are excellent. Do not migrate unless you have a concrete problem that the other database solves.</p>`,
  10: `<p>Running a remote team across time zones is hard. Here is the playbook we use to keep ProjectHub distributed team aligned and productive.</p><h2>Async first</h2><p>We default to written communication. Every decision, update, and discussion happens in ProjectHub tasks or comments before it happens in a meeting. This creates a searchable record and respects everyone time zone.</p><h2>Overlap hours</h2><p>We have a two-hour overlap window where all team members are expected to be available. This is when we hold our one weekly all-hands and any urgent discussions.</p><h2>Documentation culture</h2><p>If it is not written down, it does not exist. Every process, decision, and piece of institutional knowledge lives in our ProjectHub docs. New team members can onboard themselves in 48 hours.</p><h2>Trust over surveillance</h2><p>We do not track hours or monitor activity. We measure output. Teams that are trusted to manage their own time consistently outperform those that are micromanaged.</p>`,
  11: `<p>AgencyFlow manages 200+ active client projects at any given time. Before ProjectHub, they were losing clients because projects were falling through the cracks.</p><h2>The challenge</h2><p>With dozens of project managers and hundreds of clients, there was no single source of truth. Clients would email asking for updates that the team did not have ready. Trust was eroding.</p><h2>The solution</h2><p>AgencyFlow set up a ProjectHub workspace for each client. Clients got view-only access to their project board, so they could check progress any time without sending an email.</p><h2>The outcome</h2><p>Client retention jumped from 65% to 89% in the first year. The support team handled 40% fewer status-update requests. Three clients specifically mentioned ProjectHub in their renewal conversations.</p>`,
  12: `<p>You have been using ProjectHub for a while, but are you using it at full speed? Here are the power features that most users never discover.</p><h2>Keyboard shortcuts</h2><p>Press T anywhere to create a new task. Press K to open the command palette. Press slash to search. These three shortcuts alone will save you 20 minutes a day.</p><h2>Bulk actions</h2><p>Hold Shift and click to select multiple tasks. Then use the bulk action bar to reassign, reprioritise, or move them all at once.</p><h2>Task templates</h2><p>Create a task template for recurring work. Every sprint kickoff, code review, or client onboarding can start from a pre-filled template with subtasks already defined.</p><h2>Saved filters</h2><p>Build a filter for my high-priority tasks due this week and save it. It will appear in your sidebar for one-click access every morning.</p><h2>Webhooks</h2><p>Connect ProjectHub to any external tool using webhooks. We have users piping task completions into Slack, Google Sheets, and custom dashboards.</p>`,
};

(async () => {
  const conn = await mysql.createConnection({
    host: 'localhost', port: 3306, user: 'root', password: '', database: 'project_management',
  });

  // Add slug column if not exists
  try {
    await conn.query('ALTER TABLE blogs ADD COLUMN slug VARCHAR(320) UNIQUE AFTER title');
    console.log('slug column added');
  } catch (e) {
    if (e.code === 'ER_DUP_FIELDNAME') console.log('slug column already exists');
    else throw e;
  }

  // Generate slugs and update content
  const [blogs] = await conn.query('SELECT id, title FROM blogs');
  for (const b of blogs) {
    const slug = slugify(b.title);
    const content = contents[b.id] || '';
    await conn.query('UPDATE blogs SET slug=?, content=? WHERE id=?', [slug, content, b.id]);
    console.log(`Updated id=${b.id} slug=${slug}`);
  }

  await conn.end();
  console.log('Done');
})().catch(e => { console.error(e.message); process.exit(1); });
